### ISSUE TITLE
Reorganize code according to Python Packaging standard

### ISSUE THREAD

**Issue by Spindel** [xlanor/CryptoKitties#3]
Moving the code  from the root directory and into a subdir, and then adding a `setup.py` file that describes this.

http://python-packaging.readthedocs.io/en/latest/minimal.html

- [x] move code (one commit, make sure that the commit doesn't alter code at the same time)
- [x] Add setup.py and an endpoint
- [x] update your service file to call the endpoint

**Comment by xlanor** [comment]
Spindel, could you take a look at the setup.py before I merge it into the master branch?
